// Excel関数のモジュール化されたインデックス

import type { CustomFormula } from './shared/types';

// 基本演算子のインポート
import { 
  MULTIPLY_OPERATOR, DIVIDE_OPERATOR, ADD_OPERATOR, SUBTRACT_OPERATOR,
  GREATER_THAN_OR_EQUAL, LESS_THAN_OR_EQUAL, GREATER_THAN, LESS_THAN, EQUAL, NOT_EQUAL
} from './00-basic-operators/basicOperatorLogic';

// 各カテゴリから関数をインポート
import { DATEDIF, TODAY, NOW, DATE, YEAR, MONTH, DAY, WEEKDAY, DAYS, EDATE, EOMONTH, TIME, HOUR, MINUTE, SECOND, WEEKNUM, DAYS360, YEARFRAC, DATEVALUE, TIMEVALUE, ISOWEEKNUM } from './04-datetime/dateLogic';
import { NETWORKDAYS, NETWORKDAYS_INTL, WORKDAY, WORKDAY_INTL } from './04-datetime/workdayLogic';

import { 
  SUMIF, COUNTIF, AVERAGEIF, SUM, AVERAGE, COUNT, MAX, MIN, ROUND,
  ABS, SQRT, POWER, MOD, INT, TRUNC, RAND, RANDBETWEEN,
  LOG, LOG10, LN, EXP, ROUNDUP, ROUNDDOWN,
  CEILING, FLOOR, SIGN, FACT, SUMIFS, COUNTIFS, AVERAGEIFS, MAXIFS, MINIFS, PRODUCT, MROUND,
  COMBIN, PERMUT, GCD, LCM, QUOTIENT,
  SUMSQ, SUMPRODUCT, EVEN, ODD, ARABIC, ROMAN, COMBINA, FACTDOUBLE, SQRTPI,
  SUMX2MY2, SUMX2PY2, SUMXMY2, MULTINOMIAL, PERMUTATIONA, BASE, DECIMAL, SUBTOTAL,
  AGGREGATE, CEILING_MATH, CEILING_PRECISE, FLOOR_MATH, FLOOR_PRECISE, ISO_CEILING, SERIESSUM,
  RANDARRAY, SEQUENCE, PI, DEGREES, RADIANS
} from './01-math-trigonometry/mathLogic';

import {
  SIN, COS, TAN, ASIN, ACOS, ATAN, ATAN2, SINH, COSH, TANH,
  ASINH, ACOSH, ATANH, CSC, SEC, COT, ACOT, CSCH, SECH, COTH, ACOTH
} from './01-math-trigonometry/trigonometricLogic';

import { 
  MEDIAN, MODE, COUNTA, COUNTBLANK, LARGE, SMALL,
  GEOMEAN, HARMEAN, TRIMMEAN, STDEV_S, STDEV_P, VAR_S, VAR_P, AVEDEV
} from './02-statistical/basicStatisticsLogic';

import {
  DEVSQ, KURT, SKEW, PEARSON, CORREL,
  STANDARDIZE, COVARIANCE_P, COVARIANCE_S, SKEW_P,
  PERCENTILE_INC, PERCENTILE_EXC, QUARTILE_INC, QUARTILE_EXC, GAMMALN
} from './02-statistical/advancedStatisticsLogic';

import {
  NORM_DIST, NORM_INV, NORM_S_DIST, NORM_S_INV, LOGNORM_DIST, LOGNORM_INV,
  T_DIST, T_DIST_2T, T_DIST_RT, CHISQ_DIST, CHISQ_DIST_RT,
  F_DIST, F_DIST_RT, BETA_DIST,
  GAMMA_DIST, EXPON_DIST, WEIBULL_DIST, BINOM_DIST,
  NEGBINOM_DIST, POISSON_DIST, HYPGEOM_DIST, CONFIDENCE_NORM,
  CONFIDENCE_T, Z_TEST, T_TEST, F_TEST, CHISQ_TEST
} from './02-statistical/distributionLogic';

import {
  T_INV, T_INV_2T, CHISQ_INV, CHISQ_INV_RT, F_INV, F_INV_RT, BETA_INV, GAMMA_INV
} from './02-statistical/inverseDistributionLogic';

import {
  SLOPE, INTERCEPT, RSQ, STEYX, FORECAST, LINEST
} from './02-statistical/regressionLogic';

import {
  FISHER, FISHERINV, PHI, GAUSS, PROB, BINOM_INV
} from './02-statistical/otherStatisticalLogic';
import {
  MODE_SNGL, MODE_MULT, RANK_AVG, RANK_EQ
} from './02-statistical/modeRankLogic';
import { NORMDIST, NORMINV, NORMSDIST, NORMSINV, BINOMDIST, POISSON, CRITBINOM, CONFIDENCE, ZTEST, BETADIST, BETAINV, CHIDIST, CHIINV, GAMMADIST, GAMMAINV, HYPGEOMDIST, PERCENTRANK_INC } from './02-statistical/legacyStatisticalLogic';
import { PERCENTILE, PERCENTRANK, QUARTILE, RANK, STDEV, STDEVP, VAR, VARP } from './02-statistical/legacyStatisticalFunctions';
import { LOGNORMDIST, LOGINV, EXPONDIST, WEIBULL, GAMMA, GAMMALN_PRECISE } from './02-statistical/otherDistributionLogic';
import { FDIST, FINV, TDIST, TINV, FTEST, TTEST, CHITEST, NEGBINOMDIST } from './02-statistical/legacyDistributionLogic';

import { 
  CONCATENATE, CONCAT, LEFT, RIGHT, MID, LEN, UPPER, LOWER, TRIM, SUBSTITUTE, FIND, SEARCH, TEXTJOIN, SPLIT,
  PROPER, VALUE, TEXT, REPT, REPLACE, CHAR, CODE, EXACT, CLEAN, T, FIXED, NUMBERVALUE, DOLLAR, UNICHAR, UNICODE,
  LENB, FINDB, SEARCHB, REPLACEB, TEXTBEFORE, TEXTAFTER, TEXTSPLIT, ASC, JIS, DBCS, PHONETIC, BAHTTEXT
} from './03-text/textLogic';

import { IF, AND, OR, NOT, IFS, XOR, TRUE, FALSE, IFERROR, IFNA } from './05-logical/logicLogic';
import { SWITCH, LET } from './05-logical/newLogicalLogic';

import { VLOOKUP, HLOOKUP, INDEX, MATCH, XLOOKUP, LOOKUP, OFFSET, INDIRECT, CHOOSE, TRANSPOSE, FILTER, SORT, UNIQUE } from './06-lookup-reference/lookupLogic';

import { JOIN, ARRAYFORMULA, QUERY, REGEXMATCH, REGEXEXTRACT, REGEXREPLACE, FLATTEN } from './13-google-sheets/googleSheetsLogic';

import { 
  ISBLANK, ISERROR, ISNA, ISTEXT, ISNUMBER, ISLOGICAL, ISEVEN, ISODD, TYPE, N,
  ISERR, ISNONTEXT, ISREF, ISFORMULA, NA, ERROR_TYPE, INFO, SHEET, SHEETS, CELL, ISBETWEEN
} from './07-information/informationLogic';

import { DSUM, DAVERAGE, DCOUNT, DCOUNTA, DMAX, DMIN, DPRODUCT, DGET } from './08-database/databaseLogic';
import { DSTDEV, DSTDEVP, DVAR, DVARP } from './08-database/statisticalDatabaseLogic';

import { PMT, PV, FV, NPV, IRR, PPMT, IPMT, RATE } from './09-financial/financialLogic';
import { NPER, XNPV, XIRR, MIRR, SLN, SYD, DB, DDB, VDB, PDURATION, RRI } from './09-financial/additionalFinancialLogic';
import { ACCRINT, ACCRINTM, DISC, DURATION, MDURATION, PRICE, YIELD } from './09-financial/bondLogic';
import { COUPDAYBS, COUPDAYS, COUPDAYSNC, COUPNCD, COUPNUM, COUPPCD } from './09-financial/couponLogic';
import { AMORDEGRC, AMORLINC, CUMIPMT, CUMPRINC } from './09-financial/depreciationLogic';
import { TBILLEQ, TBILLPRICE, TBILLYIELD, DOLLARDE, DOLLARFR, EFFECT, NOMINAL, PRICEDISC, RECEIVED, INTRATE, PRICEMAT, YIELDDISC, YIELDMAT } from './09-financial/treasuryLogic';
import { ODDFPRICE, ODDFYIELD, ODDLPRICE, ODDLYIELD } from './09-financial/oddPeriodLogic';
import { ISPMT } from './09-financial/additionalFinancialLogic';

import { CONVERT, BIN2DEC, DEC2BIN, HEX2DEC, DEC2HEX, BIN2HEX, HEX2BIN, OCT2DEC, DEC2OCT, BIN2OCT, HEX2OCT, OCT2BIN, OCT2HEX } from './10-engineering/engineeringLogic';
import { 
  COMPLEX, IMABS, IMAGINARY, IMREAL, IMARGUMENT, IMCONJUGATE, IMSUM, IMSUB, 
  IMPRODUCT, IMDIV, IMPOWER, IMSQRT, IMEXP, IMLN, IMLOG10, IMLOG2 
} from './10-engineering/complexNumberLogic';
import { 
  IMSIN, IMCOS, IMTAN, IMSINH, IMCOSH, IMCSC, IMSEC, IMCOT, IMCSCH, IMSECH 
} from './10-engineering/complexTrigLogic';
import { BESSELI, BESSELJ, BESSELK, BESSELY } from './10-engineering/besselLogic';
import { ERF, ERF_PRECISE, ERFC, ERFC_PRECISE, DELTA, GESTEP } from './10-engineering/errorLogic';
import { BITAND, BITOR, BITXOR, BITLSHIFT, BITRSHIFT } from './10-engineering/bitLogic';
import { 
  ROW, ROWS, COLUMN, COLUMNS, ADDRESS, AREAS, FORMULATEXT, XMATCH, LAMBDA, 
  HYPERLINK, CHOOSEROWS, CHOOSECOLS, GETPIVOTDATA 
} from './06-lookup-reference/additionalLookupLogic';

import {
  SORTBY, TAKE, DROP, EXPAND, HSTACK, VSTACK, TOCOL, TOROW, WRAPROWS, WRAPCOLS
} from './06-lookup-reference/dynamicArrayLogic';

import {
  BYROW, BYCOL, MAP, REDUCE, SCAN, MAKEARRAY
} from './06-lookup-reference/lambdaArrayLogic';

import { MDETERM, MINVERSE, MMULT, MUNIT } from './01-math-trigonometry/matrixLogic';
import { WEBSERVICE, FILTERXML, ENCODEURL } from './12-web/webLogic';
import { IMPORTDATA, IMPORTFEED, IMPORTHTML, IMPORTXML, IMPORTRANGE, IMAGE } from './12-web/importLogic';
import { CUBEVALUE, CUBEMEMBER, CUBESET, CUBESETCOUNT, CUBERANKEDMEMBER, CUBEMEMBERPROPERTY, CUBEKPIMEMBER } from './11-cube/cubeLogic';
import { ISOMITTED, STOCKHISTORY, GPT } from './14-others/excelNewLogic';
import { SORTN, SPARKLINE, GOOGLETRANSLATE, DETECTLANGUAGE, GOOGLEFINANCE, TO_DATE, TO_PERCENT, TO_DOLLARS, TO_TEXT } from './13-google-sheets/googleSheetsExtraLogic';

// すべての関数を配列にまとめる
export const ALL_FUNCTIONS = [
  // 01. 数学・三角関数（関数を先に評価）
  ...Object.values({
    SUMIF, COUNTIF, AVERAGEIF, SUM, AVERAGE, COUNT, MAX, MIN, MROUND, ROUND,
    ABS, SQRT, POWER, MOD, INT, TRUNC, RAND, RANDBETWEEN,
    LOG, LOG10, LN, EXP, ROUNDUP, ROUNDDOWN,
    CEILING, FLOOR, SIGN, FACT, SUMIFS, COUNTIFS, AVERAGEIFS, MAXIFS, MINIFS, PRODUCT,
    COMBIN, PERMUT, GCD, LCM, QUOTIENT,
    SUMSQ, SUMPRODUCT, EVEN, ODD, ARABIC, ROMAN, COMBINA, FACTDOUBLE, SQRTPI,
    SUMX2MY2, SUMX2PY2, SUMXMY2, MULTINOMIAL, PERMUTATIONA, BASE, DECIMAL, SUBTOTAL,
    AGGREGATE, CEILING_MATH, CEILING_PRECISE, FLOOR_MATH, FLOOR_PRECISE, ISO_CEILING, SERIESSUM,
    RANDARRAY, SEQUENCE, PI, DEGREES, RADIANS,
    ASIN, ACOS, ATAN, ATAN2, ASINH, ACOSH, ATANH, ACOT, ACOTH,
    SIN, COS, TAN, SINH, COSH, TANH, CSC, SEC, COT, CSCH, SECH, COTH
  }),

  // 02. 統計関数
  ...Object.values({
    MEDIAN, MODE, COUNTA, COUNTBLANK, LARGE, SMALL,
    GEOMEAN, HARMEAN, TRIMMEAN, STDEV_S, STDEV_P, VAR_S, VAR_P, AVEDEV,
    DEVSQ, KURT, SKEW, PEARSON, CORREL,
    STANDARDIZE, COVARIANCE_P, COVARIANCE_S, SKEW_P,
    PERCENTILE_INC, PERCENTILE_EXC, QUARTILE_INC, QUARTILE_EXC, GAMMALN,
    NORM_DIST, NORM_INV, NORM_S_DIST, NORM_S_INV, LOGNORM_DIST, LOGNORM_INV,
    T_DIST, T_DIST_2T, T_DIST_RT, CHISQ_DIST, CHISQ_DIST_RT,
    F_DIST, F_DIST_RT, BETA_DIST,
    GAMMA_DIST, EXPON_DIST, WEIBULL_DIST, BINOM_DIST,
    NEGBINOM_DIST, POISSON_DIST, HYPGEOM_DIST, CONFIDENCE_NORM,
    CONFIDENCE_T, Z_TEST, T_TEST, F_TEST, CHISQ_TEST,
    T_INV, T_INV_2T, CHISQ_INV, CHISQ_INV_RT, F_INV, F_INV_RT, BETA_INV, GAMMA_INV,
    SLOPE, INTERCEPT, RSQ, STEYX, FORECAST, LINEST,
    FISHER, FISHERINV, PHI, GAUSS, PROB, BINOM_INV,
    MODE_SNGL, MODE_MULT, RANK_AVG, RANK_EQ,
    NORMDIST, NORMINV, NORMSDIST, NORMSINV, BINOMDIST, POISSON, CRITBINOM, CONFIDENCE, ZTEST,
    LOGNORMDIST, LOGINV, EXPONDIST, WEIBULL, GAMMADIST, GAMMAINV, BETADIST, BETAINV, CHIDIST, CHIINV, HYPGEOMDIST,
    FDIST, FINV, TDIST, TINV, FTEST, TTEST, CHITEST, NEGBINOMDIST,
    PERCENTILE, PERCENTRANK, QUARTILE, RANK, STDEV, STDEVP, VAR, VARP,
    GAMMA, GAMMALN_PRECISE, PERCENTRANK_INC
  }),

  // 03. 文字列操作関数
  ...Object.values({
    CONCATENATE, CONCAT, LEFT, RIGHT, MID, LEN, UPPER, LOWER, TRIM, SUBSTITUTE, FIND, SEARCH, TEXTJOIN,
    PROPER, VALUE, TEXT, REPT, REPLACE, CHAR, CODE, EXACT, CLEAN, T, FIXED, NUMBERVALUE, DOLLAR, UNICHAR, UNICODE,
    LENB, FINDB, SEARCHB, REPLACEB, TEXTBEFORE, TEXTAFTER, TEXTSPLIT, ASC, JIS, DBCS, PHONETIC, BAHTTEXT
  }),

  // 04. 日付・時刻関数
  ...Object.values({
    DATEDIF, NETWORKDAYS, TODAY, NOW, DATE, YEAR, MONTH, DAY, WEEKDAY, DAYS, EDATE, EOMONTH, TIME, HOUR, MINUTE, SECOND, WEEKNUM, DAYS360, YEARFRAC, DATEVALUE, TIMEVALUE, ISOWEEKNUM, NETWORKDAYS_INTL, WORKDAY, WORKDAY_INTL
  }),

  // 05. 論理関数
  ...Object.values({
    IF, AND, OR, NOT, IFS, XOR, TRUE, FALSE, IFERROR, IFNA, SWITCH, LET
  }),

  // 06. 検索・参照関数
  ...Object.values({
    VLOOKUP, HLOOKUP, INDEX, MATCH, XLOOKUP, LOOKUP, OFFSET, INDIRECT, CHOOSE, TRANSPOSE, FILTER, SORT, UNIQUE,
    ROW, ROWS, COLUMN, COLUMNS, ADDRESS, AREAS, FORMULATEXT, XMATCH, LAMBDA, HYPERLINK, CHOOSEROWS, CHOOSECOLS, GETPIVOTDATA,
    SORTBY, TAKE, DROP, EXPAND, HSTACK, VSTACK, TOCOL, TOROW, WRAPROWS, WRAPCOLS,
    BYROW, BYCOL, MAP, REDUCE, SCAN, MAKEARRAY
  }),

  // 07. 情報関数
  ...Object.values({
    ISBLANK, ISERROR, ISNA, ISTEXT, ISNUMBER, ISLOGICAL, ISEVEN, ISODD, TYPE, N,
    ISERR, ISNONTEXT, ISREF, ISFORMULA, NA, ERROR_TYPE, INFO, SHEET, SHEETS, CELL, ISBETWEEN
  }),

  // 08. データベース関数
  ...Object.values({
    DSUM, DAVERAGE, DCOUNT, DCOUNTA, DMAX, DMIN, DPRODUCT, DGET, DSTDEV, DSTDEVP, DVAR, DVARP
  }),

  // 09. 財務関数
  ...Object.values({
    PMT, PV, FV, NPV, IRR, PPMT, IPMT, RATE, NPER, XNPV, XIRR, MIRR, SLN, SYD, DB, DDB, VDB, PDURATION, RRI, ISPMT,
    ACCRINT, ACCRINTM, DISC, DURATION, MDURATION, PRICE, YIELD,
    COUPDAYBS, COUPDAYS, COUPDAYSNC, COUPNCD, COUPNUM, COUPPCD,
    AMORDEGRC, AMORLINC, CUMIPMT, CUMPRINC,
    TBILLEQ, TBILLPRICE, TBILLYIELD, DOLLARDE, DOLLARFR, EFFECT, NOMINAL, PRICEDISC, RECEIVED, INTRATE, PRICEMAT, YIELDDISC, YIELDMAT,
    ODDFPRICE, ODDFYIELD, ODDLPRICE, ODDLYIELD
  }),

  // 10. エンジニアリング関数
  ...Object.values({
    CONVERT, BIN2DEC, DEC2BIN, HEX2DEC, DEC2HEX, BIN2HEX, HEX2BIN, OCT2DEC, DEC2OCT, BIN2OCT, HEX2OCT, OCT2BIN, OCT2HEX,
    COMPLEX, IMABS, IMAGINARY, IMREAL, IMARGUMENT, IMCONJUGATE, IMSUM, IMSUB, 
    IMPRODUCT, IMDIV, IMPOWER, IMSQRT, IMEXP, IMLN, IMLOG10, IMLOG2,
    IMSIN, IMCOS, IMTAN, IMSINH, IMCOSH, IMCSC, IMSEC, IMCOT, IMCSCH, IMSECH,
    BESSELI, BESSELJ, BESSELK, BESSELY,
    ERF, ERF_PRECISE, ERFC, ERFC_PRECISE, DELTA, GESTEP,
    BITAND, BITOR, BITXOR, BITLSHIFT, BITRSHIFT
  }),

  // 15. その他 (行列関数など)
  ...Object.values({
    MDETERM, MINVERSE, MMULT, MUNIT,
    CUBEVALUE, CUBEMEMBER, CUBESET, CUBESETCOUNT, CUBERANKEDMEMBER, CUBEMEMBERPROPERTY, CUBEKPIMEMBER,
    ISOMITTED, STOCKHISTORY, GPT
  }),

  // 12. Web関数
  ...Object.values({
    WEBSERVICE, FILTERXML, ENCODEURL,
    IMPORTDATA, IMPORTFEED, IMPORTHTML, IMPORTXML, IMPORTRANGE, IMAGE
  }),

  // 16. Google Sheets関数
  ...Object.values({
    JOIN, ARRAYFORMULA, QUERY, REGEXMATCH, REGEXEXTRACT, REGEXREPLACE, FLATTEN,
    SORTN, SPARKLINE, GOOGLETRANSLATE, DETECTLANGUAGE, GOOGLEFINANCE, TO_DATE, TO_PERCENT, TO_DOLLARS, TO_TEXT
  }),
  
  // 00. 基本演算子（最後に評価）
  GREATER_THAN_OR_EQUAL, LESS_THAN_OR_EQUAL, NOT_EQUAL, GREATER_THAN, LESS_THAN, EQUAL,
  MULTIPLY_OPERATOR, DIVIDE_OPERATOR, 
  ADD_OPERATOR, SUBTRACT_OPERATOR
] as CustomFormula[];

// カテゴリ別の関数分類
export const FUNCTION_CATEGORIES = {
  mathTrigonometry: [
    SUMIF, COUNTIF, AVERAGEIF, SUM, AVERAGE, COUNT, MAX, MIN, MROUND, ROUND,
    ABS, SQRT, POWER, MOD, INT, TRUNC, RAND, RANDBETWEEN,
    LOG, LOG10, LN, EXP, ROUNDUP, ROUNDDOWN,
    CEILING, FLOOR, SIGN, FACT, SUMIFS, COUNTIFS, AVERAGEIFS, MAXIFS, MINIFS, PRODUCT,
    COMBIN, PERMUT, GCD, LCM, QUOTIENT,
    SUMSQ, SUMPRODUCT, EVEN, ODD, ARABIC, ROMAN, COMBINA, FACTDOUBLE, SQRTPI,
    SUMX2MY2, SUMX2PY2, SUMXMY2, MULTINOMIAL, PERMUTATIONA, BASE, DECIMAL, SUBTOTAL,
    AGGREGATE, CEILING_MATH, CEILING_PRECISE, FLOOR_MATH, FLOOR_PRECISE, ISO_CEILING, SERIESSUM,
    RANDARRAY, SEQUENCE,
    SIN, COS, TAN, ASIN, ACOS, ATAN, ATAN2, SINH, COSH, TANH,
    ASINH, ACOSH, ATANH, CSC, SEC, COT, ACOT, CSCH, SECH, COTH, ACOTH,
    MDETERM, MINVERSE, MMULT, MUNIT
  ] as CustomFormula[],
  statistical: [
    MEDIAN, MODE, COUNTA, COUNTBLANK, LARGE, SMALL,
    GEOMEAN, HARMEAN, TRIMMEAN, STDEV_S, STDEV_P, VAR_S, VAR_P,
    DEVSQ, KURT, SKEW, PEARSON, CORREL,
    STANDARDIZE, COVARIANCE_P, COVARIANCE_S, SKEW_P,
    PERCENTILE_INC, PERCENTILE_EXC, QUARTILE_INC, QUARTILE_EXC, GAMMALN,
    NORM_DIST, NORM_INV, NORM_S_DIST, NORM_S_INV, LOGNORM_DIST, LOGNORM_INV,
    T_DIST, T_DIST_2T, T_DIST_RT, CHISQ_DIST, CHISQ_DIST_RT,
    F_DIST, F_DIST_RT, BETA_DIST,
    GAMMA_DIST, EXPON_DIST, WEIBULL_DIST, BINOM_DIST,
    NEGBINOM_DIST, POISSON_DIST, HYPGEOM_DIST, CONFIDENCE_NORM,
    CONFIDENCE_T, Z_TEST, T_TEST, F_TEST, CHISQ_TEST,
    T_INV, T_INV_2T, CHISQ_INV, CHISQ_INV_RT, F_INV, F_INV_RT, BETA_INV, GAMMA_INV,
    SLOPE, INTERCEPT, RSQ, STEYX, FORECAST, LINEST,
    FISHER, FISHERINV, PHI, GAUSS, PROB, BINOM_INV,
    MODE_SNGL, MODE_MULT, RANK_AVG, RANK_EQ,
    NORMDIST, NORMINV, NORMSDIST, NORMSINV, BINOMDIST, POISSON, CRITBINOM, CONFIDENCE, ZTEST,
    LOGNORMDIST, LOGINV, EXPONDIST, WEIBULL, GAMMADIST, GAMMAINV, BETADIST, BETAINV, CHIDIST, CHIINV, HYPGEOMDIST,
    FDIST, FINV, TDIST, TINV, FTEST, TTEST, CHITEST, NEGBINOMDIST,
    PERCENTILE, PERCENTRANK, QUARTILE, RANK, STDEV, STDEVP, VAR, VARP
  ] as CustomFormula[],
  text: [
    CONCATENATE, CONCAT, LEFT, RIGHT, MID, LEN, UPPER, LOWER, TRIM, SUBSTITUTE, FIND, SEARCH, TEXTJOIN, SPLIT,
    PROPER, VALUE, TEXT, REPT, REPLACE, CHAR, CODE, EXACT, CLEAN, T, FIXED, NUMBERVALUE, DOLLAR, UNICHAR, UNICODE,
    LENB, FINDB, SEARCHB, REPLACEB, TEXTBEFORE, TEXTAFTER, TEXTSPLIT, ASC, JIS, DBCS, PHONETIC, BAHTTEXT
  ] as CustomFormula[],
  datetime: [
    DATEDIF, NETWORKDAYS, TODAY, NOW, DATE, YEAR, MONTH, DAY, WEEKDAY, DAYS, EDATE, EOMONTH, TIME, HOUR, MINUTE, SECOND, WEEKNUM, DAYS360, YEARFRAC, DATEVALUE, TIMEVALUE, ISOWEEKNUM, NETWORKDAYS_INTL, WORKDAY, WORKDAY_INTL
  ] as CustomFormula[],
  logical: [IF, AND, OR, NOT, IFS, XOR, TRUE, FALSE, IFERROR, IFNA, SWITCH, LET] as CustomFormula[],
  lookupReference: [
    VLOOKUP, HLOOKUP, INDEX, MATCH, XLOOKUP, LOOKUP, OFFSET, INDIRECT, CHOOSE, TRANSPOSE, FILTER, SORT, UNIQUE,
    ROW, ROWS, COLUMN, COLUMNS, ADDRESS, AREAS, FORMULATEXT, XMATCH, LAMBDA, HYPERLINK, CHOOSEROWS, CHOOSECOLS,
    SORTBY, TAKE, DROP, EXPAND, HSTACK, VSTACK, TOCOL, TOROW, WRAPROWS, WRAPCOLS
  ] as CustomFormula[],
  information: [
    ISBLANK, ISERROR, ISNA, ISTEXT, ISNUMBER, ISLOGICAL, ISEVEN, ISODD, TYPE, N,
    ISERR, ISNONTEXT, ISREF, ISFORMULA, NA, ERROR_TYPE, INFO, SHEET, SHEETS, CELL, ISBETWEEN
  ] as CustomFormula[],
  database: [DSUM, DAVERAGE, DCOUNT, DCOUNTA, DMAX, DMIN, DPRODUCT, DGET, DSTDEV, DSTDEVP, DVAR, DVARP] as CustomFormula[],
  financial: [PMT, PV, FV, NPV, IRR, PPMT, IPMT, RATE, NPER, XNPV, XIRR, MIRR, SLN, SYD, DB, DDB, VDB, PDURATION, RRI] as CustomFormula[],
  engineering: [
    CONVERT, BIN2DEC, DEC2BIN, HEX2DEC, DEC2HEX, BIN2HEX, HEX2BIN, OCT2DEC, DEC2OCT, BIN2OCT, HEX2OCT, OCT2BIN, OCT2HEX,
    COMPLEX, IMABS, IMAGINARY, IMREAL, IMARGUMENT, IMCONJUGATE, IMSUM, IMSUB, 
    IMPRODUCT, IMDIV, IMPOWER, IMSQRT, IMEXP, IMLN, IMLOG10, IMLOG2,
    IMSIN, IMCOS, IMTAN, IMSINH, IMCOSH, IMCSC, IMSEC, IMCOT, IMCSCH, IMSECH,
    BESSELI, BESSELJ, BESSELK, BESSELY,
    ERF, ERF_PRECISE, ERFC, ERFC_PRECISE, DELTA, GESTEP,
    BITAND, BITOR, BITXOR, BITLSHIFT, BITRSHIFT
  ] as CustomFormula[],
  web: [WEBSERVICE, FILTERXML, ENCODEURL, IMPORTDATA, IMPORTFEED, IMPORTHTML, IMPORTXML, IMPORTRANGE, IMAGE] as CustomFormula[],
  googleSheets: [JOIN, ARRAYFORMULA, QUERY, REGEXMATCH, REGEXEXTRACT, REGEXREPLACE, FLATTEN, SORTN, SPARKLINE, GOOGLETRANSLATE, DETECTLANGUAGE, GOOGLEFINANCE, TO_DATE, TO_PERCENT, TO_DOLLARS, TO_TEXT] as CustomFormula[],
  cube: [CUBEVALUE, CUBEMEMBER, CUBESET, CUBESETCOUNT, CUBERANKEDMEMBER, CUBEMEMBERPROPERTY, CUBEKPIMEMBER] as CustomFormula[],
  others: [ISOMITTED, STOCKHISTORY, GPT] as CustomFormula[]
};

// 全ての関数（HyperFormulaは使用しない）
export const MANUAL_FUNCTIONS = ALL_FUNCTIONS;

// 関数名で検索
export const findFunction = (name: string): CustomFormula | undefined => {
  return ALL_FUNCTIONS.find(f => f.name.toUpperCase() === name.toUpperCase());
};

// 関数のパターンマッチング
export const matchFormula = (formula: string): { function: CustomFormula; matches: RegExpMatchArray } | null => {
  for (const func of ALL_FUNCTIONS) {
    const matches = formula.match(func.pattern);
    if (matches) {
      return { function: func, matches };
    }
  }
  
  return null;
};

// getFunctionType is exported from definitions/functionDefinitions.ts

// エクスポート
export * from './shared/types';
export * from './shared/utils';
export { 
  SUMIF, COUNTIF, AVERAGEIF, SUM, AVERAGE, COUNT, MAX, MIN, MROUND, ROUND,
  ABS, SQRT, POWER, MOD, INT, TRUNC, RAND, RANDBETWEEN,
  LOG, LOG10, LN, EXP, ROUNDUP, ROUNDDOWN,
  CEILING, FLOOR, SIGN, FACT, SUMIFS, COUNTIFS, AVERAGEIFS, MAXIFS, MINIFS, PRODUCT,
  COMBIN, PERMUT, GCD, LCM, QUOTIENT,
  SUMSQ, SUMPRODUCT, EVEN, ODD, ARABIC, ROMAN, COMBINA, FACTDOUBLE, SQRTPI,
  SUMX2MY2, SUMX2PY2, SUMXMY2, MULTINOMIAL, PERMUTATIONA, BASE, DECIMAL, SUBTOTAL,
  AGGREGATE, CEILING_MATH, CEILING_PRECISE, FLOOR_MATH, FLOOR_PRECISE, ISO_CEILING, SERIESSUM,
  RANDARRAY, SEQUENCE
} from './01-math-trigonometry/mathLogic';
export * from './01-math-trigonometry/trigonometricLogic';
export * from './02-statistical/basicStatisticsLogic';
export * from './02-statistical/advancedStatisticsLogic';
export * from './02-statistical/distributionLogic';
export * from './02-statistical/inverseDistributionLogic';
export * from './02-statistical/regressionLogic';
export * from './02-statistical/otherStatisticalLogic';
export * from './02-statistical/modeRankLogic';
export * from './03-text/textLogic';
export * from './04-datetime/dateLogic';
export * from './04-datetime/workdayLogic';
export * from './05-logical/logicLogic';
export * from './05-logical/newLogicalLogic';
export * from './06-lookup-reference/lookupLogic';
export * from './07-information/informationLogic';
export * from './08-database/databaseLogic';
export * from './09-financial/financialLogic';
export * from './09-financial/additionalFinancialLogic';
export * from './10-engineering/engineeringLogic';
export * from './10-engineering/complexNumberLogic';
export * from './10-engineering/complexTrigLogic';
export * from './10-engineering/besselLogic';
export * from './10-engineering/errorLogic';
export * from './10-engineering/bitLogic';
export * from './06-lookup-reference/additionalLookupLogic';
export * from './06-lookup-reference/dynamicArrayLogic';
export * from './06-lookup-reference/lambdaArrayLogic';
export * from './08-database/statisticalDatabaseLogic';
export * from './12-web/webLogic';
export * from './01-math-trigonometry/matrixLogic';
export * from './11-cube/cubeLogic';
export * from './13-google-sheets/googleSheetsLogic';
export * from './13-google-sheets/googleSheetsExtraLogic';
export * from './14-others/excelNewLogic';
export * from './02-statistical/legacyStatisticalLogic';
export * from './02-statistical/legacyStatisticalFunctions';
export * from './02-statistical/otherDistributionLogic';
export * from './02-statistical/legacyDistributionLogic';
export * from './09-financial/bondLogic';
export * from './09-financial/couponLogic';
export * from './09-financial/depreciationLogic';
export * from './09-financial/treasuryLogic';
export * from './09-financial/oddPeriodLogic';